version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madarassa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://db:5432/madarassa
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      #JWT_SECRET: your-jwt-secret
      #SUPABASE_API_KEY: your-supabase-key
      #SUPABASE_URL: https://your-project.supabase.co
      #SUPABASE_BUCKET: uploads

    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: