services:
  - type: web
    name: mdarassa-api
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromSecret: SUPABASE_DB_URL
      - key: DB_USERNAME
        fromSecret: DB_USERNAME
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_API_KEY
        fromSecret: SUPABASE_API_KEY
      - key: SUPABASE_BUCKET
        value: folders
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
    numInstances: 1
    healthCheckPath: /actuator/health
    autoDeploy: true