services:
  - type: web
    name: mdrassa-api
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromSecret: DB_URL
      - key: DB_USERNAME
        fromSecret: DB_USERNAME
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_BUCKET
        fromSecret: SUPABASE_BUCKET
      - key: SUPABASE_API_KEY
        fromSecret: SUPABASE_API_KEY
    healthCheckPath: /actuator/health